#!/bin/sh

if [ $# -eq 3 ]
 then

  if [ $1 -gt $2 ]
   then 
    VALOR=$1
   else
    VALOR=$2
   fi

   if [ $3 -gt $VALOR ]
     then
      VALOR=$3
    fi

  echo "El mayor de los 3 valores es: $VALOR "

 else
  echo "Ingreso incompleto de parametros"  
fi

